### ISSUE TITLE
[FR] Search for spotify playlist by playlist id

### ISSUE THREAD

**Issue by chrisbehectik** [kamilkosek/jellyplist#17]
I believe, currently, the search function only searches for playlist names. Would be great to search by playlist id. I have a few friends that have banger playlists I would like on my jellyfin server.

**Comment by kamilkosek** [comment]
Thanks for reaching out, will implement this . 
Also user authorization code flow will be possilble. This way you can authorize your personal spotify profile and import playlists from there

**Comment by kamilkosek** [comment]
You can now drop a link to a playlist on the first page in v 0.1.7.

Please take look at the release notes , as there are some changes which might take action from your side.
https://github.com/kamilkosek/jellyplist/releases/tag/0.1.7

**Comment by chrisbehectik** [comment]
Thanks for implementing this! I'm trying things out as we speak.

I get the below error because the cover of the playlist is a webp image. It doesn't allow me to pull it into Jellyfin because of this.
![image](https://github.com/user-attachments/assets/27a3ab14-c143-4a70-b612-b8da35f34dbd)

**Comment by kamilkosek** [comment]
@chrisbehectik would you mind sharing the playlist id ? If  its not possible, could you post some logs from the app ? 
Im curious to see whats happening there :D

**Comment by chrisbehectik** [comment]
Sure. https://open.spotify.com/playlist/78yIzaK1GzKPCoDpTEfack

**Comment by kamilkosek** [comment]
@chrisbehectik strange, added it without any issues. Could you update to the latest 0.1.8 release and try again ? If its happening again, could you share some logs ?

**Comment by chrisbehectik** [comment]
I'm updated to the latest version. I want to add a little correction, it seems like it adds the playlist to jellyfin and starts downloading the songs but it doesn't pull the playlist cover.

Below a screenshot of some of the playlists I've added to jellyplist that show on jellyfin. Only the "Public" playlists seem to have imported the cover art.

![image](https://github.com/user-attachments/assets/95e4b413-0e00-4c29-b1f7-95d5121b3778)

**Comment by kamilkosek** [comment]
Ah ok, do you have a different theme enabled in jellyfin ? 
Besides that, I will do some rework on the Jellyfin Client Implementation to better catch such cases.

**Comment by chrisbehectik** [comment]
I do have some custom CSS to make my jellyfin look a bit like netflix with a Christmasy twist to it. Would that cause any issues?

**Comment by kamilkosek** [comment]
Nah, I dont think so, the error you are getting  seems to be originated directly from the jellyfin api. We will figure it out ;)

**Comment by kamilkosek** [comment]
Ok, the issue with the unsupported image is identified thanks to @artyorsh and will be fixed in the next release

**Comment by kamilkosek** [comment]
I will close this one, as the initial request is already fulfilled. Feel free to open a new issue if somethings goes wrong
