### ISSUE TITLE
Artist Similarity to Identify Existing Tracks

### ISSUE THREAD

**Issue by NovaCyntax** [kamilkosek/jellyplist#24]
Current implementation of this may be a bit too loose. For example, a playlist contained a song titled "dotCOM" by the artist "NANORAY", and Jellyplist incorrectly identified it as already existing in my library (it found a song that contained "(Dotcom Remix)" in the title, which confused it). 

Suggestion: Consider using artist similarity to identify existing tracks as well

**Comment by kamilkosek** [comment]
I see the issue here, thanks again a lot for reaching out. 👍  Give me 20 minutes for a new dev build 🌮

**Comment by NovaCyntax** [comment]
Re-running test build now, have been traveling for Thanksgiving. Will hopefully have good results.

**Comment by NovaCyntax** [comment]
The same behavior described above appears to be happening despite the change. It appears as if Jellyplist is choosing to not download the song entirely, if the correct song was already present it seems as if it would choose it correctly.

**Comment by NovaCyntax** [comment]
Just noticed on the most recent build that this was fixed.
