### ISSUE TITLE
Really Bad Timing 

### ISSUE THREAD

**Issue by kamilkosek** [kamilkosek/jellyplist#25]
As of 2024-11-27 spotify has deprecated some API endpoints which were used by Jellyplist
[https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api](https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api)

**Comment by kamilkosek** [comment]
So, Spotify decided to deprecate the API-Endpoints which made it possible to browse and discover playlists. While this seems not to be a big issue, the real problem is that you can´t retrieve playlist details of `Algorithmic and Spotify-owned editorial playlists` , like `Top 50 Germany`.  These playlists usaully are easily to identify, the ID starts with `37i9dQZF1..........`

I already got a plan to at least mitigate the second issue , but browsing should be done via the Spotify-Web App

**Comment by joestump** [comment]
Darn. Just ran into this after installing this. App loads fine, but Featured/Categories both fail with 404s in the logs. Search is also failing, but not clear why.

**Comment by kamilkosek** [comment]
This is actually a genius idea. I will implement this. 
but keep in mind that Algorithmic and Spotify-owned editorial playlists (starting with id 37i9dQZF1) won’t work.
Search will work in the next dev release today.

**Comment by mrxorao** [comment]
"spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/browse/categories/0JQ5DAt0tbjZptfcdMSKl3/playlists?limit=16&offset=0:

 Not Found, reason: None" 
 
 I have this error, is it because of the Spotify update or some wrong configuration on my part?

**Comment by kamilkosek** [comment]
@mrxorao Unforturenately it´s caused by the changes made by Spotify. 
I try to cobble together an experimental API Client, to at least make it work to add manually Algorithmic and Spotify-owned editorial playlists.

**Comment by kamilkosek** [comment]
Yesterday I pushed a dev container, you can test it, but there isn’t any documentation on the lidarr integration or the new Spotify api client , yet…

**Comment by kamilkosek** [comment]
@joestump  I am going to close this one now. If you encounter any issues or got some questions, just reach out 💯
