### ISSUE TITLE
I cant unlock blocked task "download_missing_tracks"	

### ISSUE THREAD

**Issue by mrxorao** [kamilkosek/jellyplist#35]
![image](https://github.com/user-attachments/assets/6b044439-6791-4d1b-b833-5887abf82bde)

Log: 
[2024-12-06 10:56:17,607][          trace.py: 128 -                    info() ]    INFO - Task app.tasks.download_missing_tracks[4b8bef46-c4a9-46d5-a81f-7ed45f8667ce] succeeded in 0.0011501050321385264s: {'status': 'Task skipped, another instance is running'}

And the option "Unlock blocked tasks" does not appear to unlock the task "download_missing_track"

**Comment by kamilkosek** [comment]
Thanks for reaching out. I have noticed this too already and fixed it in my local dev environment, will be pushed out today.

**Comment by mrxorao** [comment]
Ok thank you very much, another thing unfortunately my server IP is blocked on youtube music, so I can't download music, I put in the jellyplist-worker environment http_proxy and https_proxy so it will already work right?

**Comment by kamilkosek** [comment]
From what I quickly saw on [https://spotdl.github.io/spotify-downloader/usage/](https://spotdl.github.io/spotify-downloader/usage/) spotDL supports passing a proxy in but it isn´t currently implemented Jellyplist. Will implement this in the next release

- [ ] Implement spotDL proxy variable
