### ISSUE TITLE
I cant delete the playlist

### ISSUE THREAD

**Issue by mrxorao** [kamilkosek/jellyplist#36]
![msedge_xCSX4ywbc9](https://github.com/user-attachments/assets/b6e22591-909d-4b61-b512-a7336bb128b8)

- There is no option to delete the playlist,
- when I click to add it, it gives this error “Unsupported image format: image/webp”

But it's already been added in jellyfin

![image](https://github.com/user-attachments/assets/b0e1928a-0ae3-4ae2-8a0d-c6bde556c15e)

**Comment by kamilkosek** [comment]
#33
