### ISSUE TITLE
Should the downloaded files be in a Artist/Album/Track.ext format?

### ISSUE THREAD

**Issue by wardy277** [kamilkosek/jellyplist#42]
This project, even as an alpha is great and just what i need to move my reliant on spotify to self hosting. I have this working and am slowly getting a decent amount of local music

All the downloaded files get saved into a __jellyplist directory. While jellyfin does pick this up, and allows matching etc. I am left with a single Album containing all the tracks

Is this by design to stop ending up with 50 albums containing just 1-2 tracks ?

**Comment by kamilkosek** [comment]
Hi, thanks for reaching out. 
Actually, regarding the Album with only one Track: A playlist usually contains (most of the times) only one track of a album and Jellyfin is indexing it. Jellyplist itself doesn´t download whole albums, there are better tools for it such as Lidarr. Jellyplist supports connecting to Lidarr and submitting Album´s or whole Artists as monitored. 

The Output Format is a thing I am working on rn, in the next 0.1.9 release, you will be able to decide how Jellyplist (or spotDL) stores the files.

**Comment by kamilkosek** [comment]
Fixed in 0.1.9,  please read the release notes carefully [https://github.com/kamilkosek/jellyplist/releases/tag/v0.1.9](https://github.com/kamilkosek/jellyplist/releases/tag/v0.1.9)
