### ISSUE TITLE
Remove cookies.txt requirement

### ISSUE THREAD

**Issue by kamilkosek** [kamilkosek/jellyplist#5]
So you don’t need an YouTube premium account

**Comment by NovaCyntax** [comment]
Would this run with a cookies.txt for a normal YouTube account? I have deployed it to my system and I'm trying to see if it's working.

**Comment by kamilkosek** [comment]
@NovaCyntax tbh, I don’t know.
maybe it will just work but the downloaded track will be just in 128kbit . 
If you have any further questions , reach out to me and we will figure it out 🤟🏼

**Comment by PratikSavla** [comment]
So I don't have a premium account and cookies.txt still work. Can confirm that downloaded track is in 126kbit.
