### ISSUE TITLE
Playlists are Added Blank

### ISSUE THREAD

**Issue by NovaCyntax** [kamilkosek/jellyplist#9]
The following are the contents of a playlist.xml generated for a Christmas playlist I tested it with:

```
<Item>
<Added>01/01/0001 00:00:00</Added>
<LockData>false</LockData>
<Overview>
Timeless heart-warming classics from 1940- 1970 for the holiday season.
</Overview>
<LocalTitle>Christmas Classics</LocalTitle>
<RunningTime>0</RunningTime>
<Tags>
<Tag>jellyplist:playlist:2</Tag>
<Tag>0 of 68 Tracks available</Tag>
</Tags>
<OwnerUserId>705bac569e0e4ce18edffe2ae122247b</OwnerUserId>
<Shares>
<Share>
<UserId>705bac56-9e0e-4ce1-8edf-fe2ae122247b</UserId>
<CanEdit>false</CanEdit>
</Share>
<Share>
<UserId>705bac56-9e0e-4ce1-8edf-fe2ae122247b</UserId>
<CanEdit>false</CanEdit>
</Share>
</Shares>
<PlaylistMediaType>Audio</PlaylistMediaType>
</Item>
```

The tracks appear to be downloading successfully according to the logs, but aren't appearing in the playlist.xml. Additionally, the songs are downloaded to the "__jellyplist" directory, but have gibberish titles. I'm guessing they somehow aren't being added to the proper folder directories, and then being populated into the playlist.xml.

**Comment by kamilkosek** [comment]
Hi, 
The file names represent the Spotify ID , that’s why they look so gibberish.
Can you post your compose file? Or at least the folder mappings ? 
I think, I just haven’t made it clear in the compose sample that you have to map it to the same folder, to which jellyfin have bound its music library.

**Comment by NovaCyntax** [comment]
'''
version: "3.2"
services:
  redis:
    image: redis:7-alpine
    container_name: redis-jellyplist
    volumes:
      - redis_data:/data
    networks:
      - jellyplist-network
  postgres:
    container_name: postgres-jellyplist
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5443:5432"
    networks:
      - jellyplist-network
    restart: unless-stopped
  
  jellyplist:
    container_name: jellyplist
    image: ghcr.io/kamilkosek/jellyplist:latest
    depends_on: 
      - postgres
      - redis
    ports:
      - "5056:5055"
    networks:
      - jellyplist-network
    volumes:
        # Map Your cookies.txt file to exac
      - /home/nova/jellyplist/cookies.txt:/jellyplist/cookies.txt 
      - /mnt/md0/Media/Music:/jellyplist_downloads
    env_file:
      - .env
    restart: unless-stopped

    # The jellyplist-worker is used to perform background tasks, such as downloads and playlist updates.
    # It is the same container, but with a different command
  jellyplist-worker:
    container_name: jellyplist-worker
    image: ghcr.io/kamilkosek/jellyplist:latest
    command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
    volumes:
      # Map Your cookies.txt file to exac
      - /home/nova/jellyplist/cookies.txt:/jellyplist/cookies.txt 
      - /mnt/md0/Media/Music:/jellyplist_downloads
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - jellyplist-network
    restart: unless-stopped

    # jellyplist-beat is used to schedule the background tasks
  jellyplist-beat:
    container_name: jellyplist-beat
    image: ghcr.io/kamilkosek/jellyplist:latest
    command: ["celery", "-A", "app.celery", "beat", "--loglevel=info"]
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - jellyplist-network
    restart: unless-stopped

networks:
  jellyplist-network:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    redis_data:
'''

The "Music" folder mapped here is where my music is located in Jellyfin. I tried looking for errors in the logs, but I didn't notice anything after a quick look.

**Comment by PratikSavla** [comment]
Hi, even I am facing the same issue. I tried building the docker image myself for raspberry pi 4. There are no errors in the logs but similar to @NovaCyntax my playlists in Jellyfin are empty.

**Comment by PratikSavla** [comment]
For all the songs it is giving similar logs:
```
[2024-11-24 07:34:02,117: WARNING/ForkPoolWorker-4] [2024-11-24 07:34:02,117] INFO in tasks: Fetching track details from Spotify: Paheliyan (4XDr8ELaUv2GWjwKiyCwht)
[2024-11-24 07:34:02,117: INFO/ForkPoolWorker-4] Fetching track details from Spotify: Paheliyan (4XDr8ELaUv2GWjwKiyCwht)
[2024-11-24 07:34:02,132: WARNING/ForkPoolWorker-4] [2024-11-24 07:34:02,131] INFO in tasks: No matching track found in Jellyfin for Paheliyan.
[2024-11-24 07:34:02,131: INFO/ForkPoolWorker-4] No matching track found in Jellyfin for Paheliyan.
[2024-11-24 07:34:02,135: WARNING/ForkPoolWorker-4] [2024-11-24 07:34:02,135] INFO in tasks: Finished updating Jellyfin IDs for all tracks.
[2024-11-24 07:34:02,135: INFO/ForkPoolWorker-4] Finished updating Jellyfin IDs for all tracks.
[2024-11-24 07:34:02,140: INFO/ForkPoolWorker-4] Task app.tasks.update_jellyfin_id_for_downloaded_tracks[3077da1a-58a5-4fba-be7b-214fe38fdd60] succeeded in 0.7115572181064636s: {'status': 'All tracks updated', 'total': 31, 'processed': 31}
```

**Comment by kamilkosek** [comment]
@PratikSavla could you please verify if one of the downloaded tracks are available in jellyfin at all ? If not, could you perform a manual library indexing in jellyfin ? I think it’s because your jellyfin haven’t yet indexed the songs

**Comment by PratikSavla** [comment]
@kamilkosek thanks. After scanning the entire library again it worked for me. Able to see the songs in the library as well as associate the track in jellyplist. Thank you once again.

**Comment by kamilkosek** [comment]
@PratikSavla fantastic, have fun and reach out again if you find further issues

**Comment by NovaCyntax** [comment]
I tested this again from scratch. Deleted all downloaded tracks, and let the script run to completion overnight. The playlists are created in Jellyfin, but they remain blank and all of the tracks remain in the "__jellyplist" directory. Unfortunately, this doesn't seem to be working on my system. For some reason, Jellyplist isn't moving tracks to the proper directories and also adding them to the playlist.xml files. My docker-compose remains unchanged from what I posted above. As for the logs you requested, I did note this:

```
[2024-11-24 17:59:21,661: ERROR/ForkPoolWorker-15] Task app.tasks.update_jellyfin_id_for_downloaded_tracks[9f56eff0-791d-449b-85a9-4c545217c5a2] raised unexpected: ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='192.168.1.14', port=8096): Read timed out. (read timeout=10)"))
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.14', port=8096): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jellyplist/app/tasks.py", line 326, in update_jellyfin_id_for_downloaded_tracks
    search_results = jellyfin.search_music_tracks(jellyfin_admin_token,track.name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jellyplist/jellyfin/client.py", line 192, in search_music_tracks
    response = requests.get(search_url, headers=self._get_headers(session_token=session_token), params=params, timeout=10)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.14', port=8096): Read timed out. (read timeout=10)
```

Which is odd, because the IP:PORT combination is accessible by all other devices and services on my network.

**Comment by kamilkosek** [comment]
@NovaCyntax that’s really odd, the login is working as intended ? 
what could be, ist that the search is really running in to a timeout as the default is 10 seconds and this could be tight esp on slow systems. 
I will make it configurable and do a dev release for you test , if you agree

**Comment by NovaCyntax** [comment]
I have a faster system, so that would be odd if it were the case, but I'm more than happy to try a test build. If you want, I can perform a specific series of actions for you to help give more insight.

**Comment by kamilkosek** [comment]
Let me just prepare a few things, I am sure we will figure it out

**Comment by kamilkosek** [comment]
OK: 
Please do the following:
add 
`LOG_LEVEL = DEBUG` and `REFRESH_LIBRARIES_AFTER_DOWNLOAD_TASK = true` to your `.env` File.
Change the image tags on all Jellyplist conaitners to `dev`
Add a Playlist, go to `Admin-> Tasks`  and run the download task, wait for it for finish. Then run `update_all_playlists_track_status` wait for it to finish and last but not least run the `update_jellyfin_id_for_downloaded_tracks` task. 
provide the  logs from `jellyplist-worker` as well as `jellyplist`

**Comment by kamilkosek** [comment]
Maybe also , don’t start the jelliplist beat container, to keep the logs clean

**Comment by NovaCyntax** [comment]
UPDATE: As expected, this was user error. In the "Key" variable of the .env file, I generated a random key. I was not aware that this was an API token generated from within Jellyfin, because in the sample .env file it mentions that the username/password are required. I misinterpreted this. Upon replacing the "Key" variable with an API token from Jellyfin, it worked beautifully. Thanks for the patience and great work so far, I can't wait to put this to work.

**Comment by PratikSavla** [comment]
@NovaCyntax  I didn’t find anywhere SECRET_KEY is jellyfin api token. It is working with random value it for me.

**Comment by NovaCyntax** [comment]
Interesting. I tried this a dozen times and that's the one thing I changed that made it work. I didn't adjust anything else on that attempt, at least I don't think.

**Comment by kamilkosek** [comment]
Thank you @NovaCyntax  for your patience, with your help I was able to identify and mitigate a ton of bugs and also get a better understanding on how people use jellyplist and set it up. 
Keep in mind: The current dev build v0.1.5-dev-b010c89 has a problem with updating the state of downloaded tracks, but I will fix it today. 

Regarding the secret key, take a look here: [https://flask.palletsprojects.com/en/stable/config/#SECRET_KEY](https://flask.palletsprojects.com/en/stable/config/#SECRET_KEY), it is a key used for securing the session cookies, so it has nothing to do with jellyplist per se, but maybe you got a copy&paste error or used some characters which are not allowed or anything like that...

Thanks again and reach out again if you have further questions.
